# Note, You need at least 1 domain and this is not free tier.
# Pricing : https://aws.amazon.com/route53/pricing/
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys route53 Setup,
    Alias Web Elastic Load Balancer to <domain>
Parameters: 

  PMDomainJira:
    Description: "A reference to the Jira FQDN domain name"
    Type: "String"

  PMDomainRds:
    Description: "A reference to the RDS FQDN domain name"
    Type: "String"

  PMHostedZone:
    Description: "A reference to the Hosted Zone"
    Type: "String"

  PMJiraLBDNSName:
    Description: "A reference to the Jira ELB DNS Name"
    Type: "String"

  PMRdsDbEndpoint:
    Description: "A reference to the RDS Url Endpoint"
    Type: "String"
  
  PMJiraLBHostedZoneId:
    Description: "A reference to the Jira ELB Hosted Zone ID"
    Type: "String"


Resources:

  Route53:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneName: !Sub "${PMHostedZone}."
      Comment: "Zone apex alias targeted to myELB LoadBalancer."
      RecordSets:
      - Name: !Sub "${PMDomainJira}."
        Type: 'A'
        AliasTarget:
          HostedZoneId: !Ref "PMJiraLBHostedZoneId"
          DNSName: !Ref "PMJiraLBDNSName"
      - Name: !Sub "${PMDomainRds}."
        Type: 'CNAME'
        TTL: '900'
        ResourceRecords:
        - !Sub "${PMRdsDbEndpoint}"

  # RdsRoute53:
  #   Type: "AWS::Route53::RecordSetGroup"
  #   Properties:
  #     HostedZoneName: !Sub "${PMHostedZone}."
  #     Comment: "CNAME redirect custom name to RDS Endpoint."
  #     Name: "${PMDomainRds}."
  #     Type: 'CNAME'
  #     TTL: '900'
  #     ResourceRecords:
  #     - !Sub "${PMRdsDbEndpoint}"
# 	RRSet with DNS name \044\173pmdomainrds\175. is not permitted in zone crytera.com.

Outputs:

  JiraRoute53:
    Description: "A reference to the Route53"
    Value: !Ref "Route53"

  # RdsRoute53:
  #   Description: "A reference to the Route53"
  #   Value: !Ref "RdsRoute53"