# Note, This template deploys a Webserver Load Balancer that exposes our Nginx Proxy services.
# Service : Nginx Service listen to port 80
# SSL Termination is at ELB
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys an Elastic Load Balancer that exposes our Jira services.

Parameters: 

  PMServerEnv:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"

  PMJiraELBSG:
    Description: "Select the Security Group to use for the ELB"
    Type: "AWS::EC2::SecurityGroup::Id"

  PMPublicSubnets:
    Description: "Subnets to launch instances into"
    Type: "List<AWS::EC2::Subnet::Id>"

  PMS3Logging:
    Description: "S3 Logging Bucket Name"
    Type: "String"

  PMDomain1CertARN:
    Description: "ARN for my domain name"
    Type: "String"

Resources:

  MyLoadBalancer:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      ConnectionSettings:
        IdleTimeout: '300'
      ConnectionDrainingPolicy:
        Enabled: "true"
        Timeout: "30"
      CrossZone: "true"
      AccessLoggingPolicy:
        EmitInterval: '5'
        Enabled: 'True'
        S3BucketName: !Ref "PMS3Logging"
        S3BucketPrefix: "ELBLogs"
      HealthCheck:
        HealthyThreshold: '6'
        Interval: '60'
        # Target: "TCP:22"
        Target: "TCP:8000"
        Timeout: '5'
        UnhealthyThreshold: '8'
      LoadBalancerName: !Sub "${PMServerEnv}-ELB"
      Listeners:
      - LoadBalancerPort: '80'
        Protocol: "HTTP"
        InstancePort: '80'
        InstanceProtocol: "HTTP"
      - LoadBalancerPort: '443'
        Protocol: "HTTPS"
        InstancePort: '8000'
        InstanceProtocol: "HTTP"
        SSLCertificateId: !Ref "PMDomain1CertARN"
        PolicyNames:
        - !Sub "${PMServerEnv}-SSLNegotiationPolicy"
      # List aws elb describe-load-balancer-policies
      Policies:
      - PolicyName: !Sub "${PMServerEnv}-SSLNegotiationPolicy"
        PolicyType: "SSLNegotiationPolicyType"
        Attributes:
        - Name: "Server-Defined-Cipher-Order"
          Value: 'true'
        - Name: "Protocol-TLSv1"
          Value: 'false'
        - Name: "Protocol-TLSv1.1"
          Value: 'false'
        - Name: "Protocol-TLSv1.2"
          Value: 'true'
        - Name: "Protocol-SSLv3"
          Value: 'false'
        - Name: "ECDHE-ECDSA-AES128-GCM-SHA256"
          Value: 'true'
        - Name: "ECDHE-ECDSA-AES128-GCM-SHA256"
          Value: 'true'
        - Name: "ECDHE-ECDSA-AES128-SHA256"
          Value: 'true'
        - Name: "ECDHE-RSA-AES128-SHA256"
          Value: 'true'
        - Name: "ECDHE-ECDSA-AES256-GCM-SHA384"
          Value: 'true'
        - Name: "ECDHE-RSA-AES256-GCM-SHA384"
          Value: 'true'
        - Name: "ECDHE-ECDSA-AES256-SHA384"
          Value: 'true'
        - Name: "ECDHE-RSA-AES256-SHA384"
          Value: 'true'
        - Name: "AES128-GCM-SHA256"
          Value: 'true'
        - Name: "AES128-SHA256"
          Value: 'true'
        - Name: "AES256-GCM-SHA384"
          Value: 'true'
        - Name: "AES256-SHA256"
          Value: 'true'
      Scheme: "internet-facing"
      SecurityGroups:
      - Ref: "PMJiraELBSG"
      Subnets:
        Ref: "PMPublicSubnets"

# Output LoadBalancer
Outputs:
  JiraLoadBalancer:
    Description: "A reference to the Jira Load Balancer"
    Value: !Ref "MyLoadBalancer"

  JiraLBDNSName:
    Description: "The URL of the Jira Load Balancer"
    Value: !GetAtt "MyLoadBalancer.DNSName"

  JiraLBHostedZoneId:
    Description: "The CanonicalHostedZoneNameID of the Jira Load Balancer"
    Value: !GetAtt "MyLoadBalancer.CanonicalHostedZoneNameID"




